{
 "title": "FinOps AI Lab",
 "tags": [
  "finops",
  "ai",
  "kubernetes",
  "opencost"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage GB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "Memory GB"
    }
   ]
  },
  {
   "title": "CPU Usage by Namespace - millicores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=~\"payments|users|staging\"}[5m])) * 1000",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace - MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"payments|users|staging\"}) / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Requested by Namespace - cores",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(namespace) (kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"payments|users|staging\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requested by Namespace - GB",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(namespace) (kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"payments|users|staging\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top Pods CPU - millicores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sum by(namespace, pod) (rate(container_cpu_usage_seconds_total{cpu=\"total\", namespace=~\"payments|users|staging\"}[5m])) * 1000)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top Pods Memory - MB",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sum by(namespace, pod) (container_memory_working_set_bytes{namespace=~\"payments|users|staging\"}) / 1024 / 1024)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}