apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-spike
  namespace: payments
  labels:
    app: cpu-spike
    team: payments
    environment: prod
    workload-type: anomaly-demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cpu-spike
  template:
    metadata:
      labels:
        app: cpu-spike
        team: payments
        environment: prod
        workload-type: anomaly-demo
    spec:
      containers:
         - name: stress
           image: alpine:latest
           command: ["sh", "-c"]
           args: ["apk add --no-cache stress-ng && stress-ng --cpu 2 --timeout 300s"]
           resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2000m"
              memory: "512Mi"